name: Build and Test ThangLong FC

on:
  push:
    branches: [ main, develop, feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment to deploy to'
        required: true
        default: 'production'
        type: choice
        options:
          - production
          - staging
      force_deploy:
        description: 'Force deployment even from non-main branch'
        required: false
        default: false
        type: boolean
      skip_tests:
        description: 'Skip running tests'
        required: false
        default: false
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build application 
      env:
        # API Configuration
        NG_APP_API_URL: ${{ secrets.NG_APP_API_URL }}
        # Firebase configuration from GitHub secrets
        NG_APP_FIREBASE_API_KEY: ${{ secrets.APIKEY }}
        NG_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.AUTHDOMAIN }}
        NG_APP_FIREBASE_PROJECT_ID: ${{ secrets.PROJECTID }}
        NG_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.STORAGEBUCKET }}
        NG_APP_FIREBASE_DATABASE_URL: ${{ secrets.DATABASEURL }}
        NG_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGINGSENDERID }}
        NG_APP_FIREBASE_APP_ID: ${{ secrets.APPID }}
        NG_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.MEASUREMENTID }}
      run: npm run build --if-present

    - name: Run tests (if available)
      if: github.event.inputs.skip_tests != 'true'
      env:
        # API Configuration
        NG_APP_API_URL: ${{ secrets.NG_APP_API_URL }}
        NG_APP_FIREBASE_API_KEY: ${{ secrets.APIKEY }}
        NG_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.AUTHDOMAIN }}
        NG_APP_FIREBASE_PROJECT_ID: ${{ secrets.PROJECTID }}
        NG_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.STORAGEBUCKET }}
        NG_APP_FIREBASE_DATABASE_URL: ${{ secrets.DATABASEURL }}
        NG_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGINGSENDERID }}
        NG_APP_FIREBASE_APP_ID: ${{ secrets.APPID }}
        NG_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.MEASUREMENTID }}
      run: npm run test --if-present || echo "No tests configured, skipping..."
      continue-on-error: true

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ matrix.node-version }}
        path: dist/
        retention-days: 5

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: |
      (github.ref == 'refs/heads/main' && github.event_name == 'push') ||
      (github.event_name == 'workflow_dispatch' && (github.ref == 'refs/heads/main' || github.event.inputs.force_deploy == 'true'))

    steps:
    - name: Deployment Info
      run: |
        echo "🚀 Starting deployment process..."
        echo "Branch: ${{ github.ref }}"
        echo "Event: ${{ github.event_name }}"
        echo "Environment: ${{ github.event.inputs.deploy_environment || 'production' }}"
        echo "Force Deploy: ${{ github.event.inputs.force_deploy || 'false' }}"

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build for production
      env:
        # API Configuration
        NG_APP_API_URL: ${{ secrets.NG_APP_API_URL }}
        # Firebase configuration from GitHub secrets
        NG_APP_FIREBASE_API_KEY: ${{ secrets.APIKEY }}
        NG_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.AUTHDOMAIN }}
        NG_APP_FIREBASE_PROJECT_ID: ${{ secrets.PROJECTID }}
        NG_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.STORAGEBUCKET }}
        NG_APP_FIREBASE_DATABASE_URL: ${{ secrets.DATABASEURL }}
        NG_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.MESSAGINGSENDERID }}
        NG_APP_FIREBASE_APP_ID: ${{ secrets.APPID }}
        NG_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.MEASUREMENTID }}
      run: npm run build

    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: ${{ secrets.GITHUB_TOKEN }}
        firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MIA_FCM_D8555 }}
        projectId: mia-fcm-d8555
        channelId: live
        target: mia-fc-management

    - name: Deployment Success
      run: |
        echo "✅ Deployment completed successfully!"
        echo "🌐 Application deployed to: https://mia-fc-management.web.app/"
        echo "📊 Environment: ${{ github.event.inputs.deploy_environment || 'production' }}"
        echo "🎯 Branch deployed: ${{ github.ref }}"